FROM centos-systemd:7

RUN yum install -y openssh-server openssh-clients \
    && yum install -y sudo \
    && yum clean all

RUN useradd ansible \
    && echo "login" | passwd ansible --stdin \
    && mkdir /home/ansible/.ssh

COPY ./keys/remote_key.pub /home/ansible/.ssh/authorized_keys

RUN chown -R ansible:ansible /home/ansible/.ssh \
    && chmod 700 /home/ansible/.ssh \
    && chmod 600 /home/ansible/.ssh/authorized_keys

RUN echo "ansible ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers
